[2021-10-29 02:57:29,376] {processor.py:163} INFO - Started process (PID=624) to work on /opt/airflow/dags/main.py
[2021-10-29 02:57:29,377] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 02:57:29,377] {logging_mixin.py:109} INFO - [2021-10-29 02:57:29,377] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 02:57:29,378] {logging_mixin.py:109} INFO - [2021-10-29 02:57:29,378] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 50
    def ageLevels(person):
      ^
IndentationError: expected an indented block
[2021-10-29 02:57:29,388] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 02:57:29,417] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.043 seconds
[2021-10-29 02:58:00,259] {processor.py:163} INFO - Started process (PID=690) to work on /opt/airflow/dags/main.py
[2021-10-29 02:58:00,283] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 02:58:00,284] {logging_mixin.py:109} INFO - [2021-10-29 02:58:00,284] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 02:58:00,285] {logging_mixin.py:109} INFO - [2021-10-29 02:58:00,285] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 50
    def ageLevels(person):
      ^
IndentationError: expected an indented block
[2021-10-29 02:58:00,295] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 02:58:00,300] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.044 seconds
[2021-10-29 02:58:01,266] {processor.py:163} INFO - Started process (PID=691) to work on /opt/airflow/dags/main.py
[2021-10-29 02:58:01,266] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 02:58:01,267] {logging_mixin.py:109} INFO - [2021-10-29 02:58:01,267] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 02:58:01,268] {logging_mixin.py:109} INFO - [2021-10-29 02:58:01,268] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 44
    training_model_tasks = [
                       ^
IndentationError: expected an indented block
[2021-10-29 02:58:01,279] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 02:58:01,288] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.025 seconds
[2021-10-29 02:58:32,289] {processor.py:163} INFO - Started process (PID=745) to work on /opt/airflow/dags/main.py
[2021-10-29 02:58:32,289] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 02:58:32,290] {logging_mixin.py:109} INFO - [2021-10-29 02:58:32,290] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 02:58:32,291] {logging_mixin.py:109} INFO - [2021-10-29 02:58:32,290] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 44
    training_model_tasks = [
                       ^
IndentationError: expected an indented block
[2021-10-29 02:58:32,301] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 02:58:32,307] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.020 seconds
[2021-10-29 02:59:02,957] {processor.py:163} INFO - Started process (PID=809) to work on /opt/airflow/dags/main.py
[2021-10-29 02:59:02,984] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 02:59:02,984] {logging_mixin.py:109} INFO - [2021-10-29 02:59:02,984] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 02:59:02,986] {logging_mixin.py:109} INFO - [2021-10-29 02:59:02,985] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 44
    training_model_tasks = [
                       ^
IndentationError: expected an indented block
[2021-10-29 02:59:02,995] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 02:59:03,001] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.045 seconds
[2021-10-29 02:59:33,682] {processor.py:163} INFO - Started process (PID=864) to work on /opt/airflow/dags/main.py
[2021-10-29 02:59:33,687] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 02:59:33,688] {logging_mixin.py:109} INFO - [2021-10-29 02:59:33,688] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 02:59:33,692] {logging_mixin.py:109} INFO - [2021-10-29 02:59:33,691] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 44
    training_model_tasks = [
                       ^
IndentationError: expected an indented block
[2021-10-29 02:59:33,710] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 02:59:33,715] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.043 seconds
[2021-10-29 03:00:04,508] {processor.py:163} INFO - Started process (PID=928) to work on /opt/airflow/dags/main.py
[2021-10-29 03:00:04,536] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:00:04,537] {logging_mixin.py:109} INFO - [2021-10-29 03:00:04,537] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:00:04,539] {logging_mixin.py:109} INFO - [2021-10-29 03:00:04,538] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 44
    training_model_tasks = [
                       ^
IndentationError: expected an indented block
[2021-10-29 03:00:04,562] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:00:04,578] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.072 seconds
[2021-10-29 03:00:14,235] {processor.py:163} INFO - Started process (PID=972) to work on /opt/airflow/dags/main.py
[2021-10-29 03:00:14,263] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:00:14,264] {logging_mixin.py:109} INFO - [2021-10-29 03:00:14,264] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:00:14,267] {logging_mixin.py:109} INFO - [2021-10-29 03:00:14,266] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:00:14,277] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:00:14,283] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.050 seconds
[2021-10-29 03:00:45,099] {processor.py:163} INFO - Started process (PID=1028) to work on /opt/airflow/dags/main.py
[2021-10-29 03:00:45,129] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:00:45,129] {logging_mixin.py:109} INFO - [2021-10-29 03:00:45,129] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:00:45,131] {logging_mixin.py:109} INFO - [2021-10-29 03:00:45,130] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:00:45,141] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:00:45,145] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.047 seconds
[2021-10-29 03:01:15,955] {processor.py:163} INFO - Started process (PID=1092) to work on /opt/airflow/dags/main.py
[2021-10-29 03:01:15,985] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:01:15,986] {logging_mixin.py:109} INFO - [2021-10-29 03:01:15,985] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:01:15,988] {logging_mixin.py:109} INFO - [2021-10-29 03:01:15,987] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:01:16,003] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:01:16,012] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.059 seconds
[2021-10-29 03:01:46,615] {processor.py:163} INFO - Started process (PID=1147) to work on /opt/airflow/dags/main.py
[2021-10-29 03:01:46,655] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:01:46,656] {logging_mixin.py:109} INFO - [2021-10-29 03:01:46,656] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:01:46,658] {logging_mixin.py:109} INFO - [2021-10-29 03:01:46,657] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:01:46,668] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:01:46,673] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.060 seconds
[2021-10-29 03:02:17,533] {processor.py:163} INFO - Started process (PID=1213) to work on /opt/airflow/dags/main.py
[2021-10-29 03:02:17,568] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:02:17,570] {logging_mixin.py:109} INFO - [2021-10-29 03:02:17,570] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:02:17,577] {logging_mixin.py:109} INFO - [2021-10-29 03:02:17,575] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:02:17,616] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:02:17,627] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.102 seconds
[2021-10-29 03:02:48,569] {processor.py:163} INFO - Started process (PID=1268) to work on /opt/airflow/dags/main.py
[2021-10-29 03:02:48,607] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:02:48,608] {logging_mixin.py:109} INFO - [2021-10-29 03:02:48,608] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:02:48,616] {logging_mixin.py:109} INFO - [2021-10-29 03:02:48,614] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:02:48,640] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:02:48,648] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.087 seconds
[2021-10-29 03:03:19,409] {processor.py:163} INFO - Started process (PID=1334) to work on /opt/airflow/dags/main.py
[2021-10-29 03:03:19,447] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:03:19,448] {logging_mixin.py:109} INFO - [2021-10-29 03:03:19,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:03:19,452] {logging_mixin.py:109} INFO - [2021-10-29 03:03:19,452] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:03:19,462] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:03:19,468] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.061 seconds
[2021-10-29 03:03:50,267] {processor.py:163} INFO - Started process (PID=1388) to work on /opt/airflow/dags/main.py
[2021-10-29 03:03:50,307] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:03:50,309] {logging_mixin.py:109} INFO - [2021-10-29 03:03:50,308] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:03:50,316] {logging_mixin.py:109} INFO - [2021-10-29 03:03:50,314] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:03:50,352] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:03:50,368] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.109 seconds
[2021-10-29 03:04:21,041] {processor.py:163} INFO - Started process (PID=1454) to work on /opt/airflow/dags/main.py
[2021-10-29 03:04:21,082] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:04:21,083] {logging_mixin.py:109} INFO - [2021-10-29 03:04:21,083] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:04:21,086] {logging_mixin.py:109} INFO - [2021-10-29 03:04:21,086] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:04:21,097] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:04:21,101] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.062 seconds
[2021-10-29 03:04:51,993] {processor.py:163} INFO - Started process (PID=1518) to work on /opt/airflow/dags/main.py
[2021-10-29 03:04:52,005] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:04:52,005] {logging_mixin.py:109} INFO - [2021-10-29 03:04:52,005] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:04:52,007] {logging_mixin.py:109} INFO - [2021-10-29 03:04:52,006] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:04:52,017] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:04:52,021] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.031 seconds
[2021-10-29 03:05:22,870] {processor.py:163} INFO - Started process (PID=1573) to work on /opt/airflow/dags/main.py
[2021-10-29 03:05:22,913] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:05:22,914] {logging_mixin.py:109} INFO - [2021-10-29 03:05:22,914] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:05:22,921] {logging_mixin.py:109} INFO - [2021-10-29 03:05:22,919] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:05:22,953] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:05:22,967] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.099 seconds
[2021-10-29 03:05:53,606] {processor.py:163} INFO - Started process (PID=1638) to work on /opt/airflow/dags/main.py
[2021-10-29 03:05:53,647] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:05:53,648] {logging_mixin.py:109} INFO - [2021-10-29 03:05:53,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:05:53,650] {logging_mixin.py:109} INFO - [2021-10-29 03:05:53,649] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:05:53,660] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:05:53,666] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.062 seconds
[2021-10-29 03:06:24,292] {processor.py:163} INFO - Started process (PID=1692) to work on /opt/airflow/dags/main.py
[2021-10-29 03:06:24,292] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:06:24,293] {logging_mixin.py:109} INFO - [2021-10-29 03:06:24,293] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:06:24,295] {logging_mixin.py:109} INFO - [2021-10-29 03:06:24,294] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:06:24,307] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:06:24,313] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.024 seconds
[2021-10-29 03:06:54,905] {processor.py:163} INFO - Started process (PID=1758) to work on /opt/airflow/dags/main.py
[2021-10-29 03:06:54,910] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:06:54,910] {logging_mixin.py:109} INFO - [2021-10-29 03:06:54,910] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:06:54,912] {logging_mixin.py:109} INFO - [2021-10-29 03:06:54,911] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:06:54,923] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:06:54,928] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.025 seconds
[2021-10-29 03:07:25,416] {processor.py:163} INFO - Started process (PID=1812) to work on /opt/airflow/dags/main.py
[2021-10-29 03:07:25,422] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:07:25,422] {logging_mixin.py:109} INFO - [2021-10-29 03:07:25,422] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:07:25,424] {logging_mixin.py:109} INFO - [2021-10-29 03:07:25,424] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:07:25,434] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:07:25,439] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.024 seconds
[2021-10-29 03:07:56,253] {processor.py:163} INFO - Started process (PID=1877) to work on /opt/airflow/dags/main.py
[2021-10-29 03:07:56,260] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:07:56,260] {logging_mixin.py:109} INFO - [2021-10-29 03:07:56,260] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:07:56,263] {logging_mixin.py:109} INFO - [2021-10-29 03:07:56,262] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:07:56,278] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:07:56,285] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.035 seconds
[2021-10-29 03:08:26,958] {processor.py:163} INFO - Started process (PID=1931) to work on /opt/airflow/dags/main.py
[2021-10-29 03:08:26,966] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:08:26,966] {logging_mixin.py:109} INFO - [2021-10-29 03:08:26,966] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:08:26,968] {logging_mixin.py:109} INFO - [2021-10-29 03:08:26,968] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:08:26,981] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:08:26,986] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.030 seconds
[2021-10-29 03:15:54,886] {processor.py:163} INFO - Started process (PID=33) to work on /opt/airflow/dags/main.py
[2021-10-29 03:15:54,887] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 03:15:54,888] {logging_mixin.py:109} INFO - [2021-10-29 03:15:54,888] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 03:15:54,890] {logging_mixin.py:109} INFO - [2021-10-29 03:15:54,889] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 7, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2021-10-29 03:15:54,902] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 03:15:54,908] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.024 seconds
[2021-10-29 07:35:34,441] {processor.py:163} INFO - Started process (PID=33) to work on /opt/airflow/dags/main.py
[2021-10-29 07:35:34,441] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 07:35:34,442] {logging_mixin.py:109} INFO - [2021-10-29 07:35:34,442] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 07:35:34,444] {logging_mixin.py:109} INFO - [2021-10-29 07:35:34,443] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 22
    as dag:
     ^
SyntaxError: invalid syntax
[2021-10-29 07:35:34,457] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 07:35:34,465] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.027 seconds
[2021-10-29 07:36:05,190] {processor.py:163} INFO - Started process (PID=98) to work on /opt/airflow/dags/main.py
[2021-10-29 07:36:05,211] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 07:36:05,212] {logging_mixin.py:109} INFO - [2021-10-29 07:36:05,212] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 07:36:05,214] {logging_mixin.py:109} INFO - [2021-10-29 07:36:05,213] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 22
    as dag:
     ^
SyntaxError: invalid syntax
[2021-10-29 07:36:05,225] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 07:36:05,230] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.048 seconds
[2021-10-29 07:36:35,935] {processor.py:163} INFO - Started process (PID=152) to work on /opt/airflow/dags/main.py
[2021-10-29 07:36:35,959] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 07:36:35,959] {logging_mixin.py:109} INFO - [2021-10-29 07:36:35,959] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 07:36:35,960] {logging_mixin.py:109} INFO - [2021-10-29 07:36:35,960] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 22
    as dag:
     ^
SyntaxError: invalid syntax
[2021-10-29 07:36:35,970] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 07:36:35,975] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.041 seconds
[2021-10-29 07:37:06,645] {processor.py:163} INFO - Started process (PID=219) to work on /opt/airflow/dags/main.py
[2021-10-29 07:37:06,647] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 07:37:06,647] {logging_mixin.py:109} INFO - [2021-10-29 07:37:06,647] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 07:37:06,649] {logging_mixin.py:109} INFO - [2021-10-29 07:37:06,648] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 22
    as dag:
     ^
SyntaxError: invalid syntax
[2021-10-29 07:37:06,660] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 07:37:06,664] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.021 seconds
[2021-10-29 07:37:37,397] {processor.py:163} INFO - Started process (PID=273) to work on /opt/airflow/dags/main.py
[2021-10-29 07:37:37,425] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 07:37:37,427] {logging_mixin.py:109} INFO - [2021-10-29 07:37:37,426] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 07:37:37,429] {logging_mixin.py:109} INFO - [2021-10-29 07:37:37,428] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 22
    as dag:
     ^
SyntaxError: invalid syntax
[2021-10-29 07:37:37,439] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 07:37:37,443] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.048 seconds
[2021-10-29 07:38:08,082] {processor.py:163} INFO - Started process (PID=340) to work on /opt/airflow/dags/main.py
[2021-10-29 07:38:08,109] {processor.py:620} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2021-10-29 07:38:08,109] {logging_mixin.py:109} INFO - [2021-10-29 07:38:08,109] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2021-10-29 07:38:08,111] {logging_mixin.py:109} INFO - [2021-10-29 07:38:08,110] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 22
    as dag:
     ^
SyntaxError: invalid syntax
[2021-10-29 07:38:08,121] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2021-10-29 07:38:08,127] {processor.py:171} INFO - Processing /opt/airflow/dags/main.py took 0.046 seconds
