[2021-11-01 00:00:21,314] {processor.py:163} INFO - Started process (PID=166) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:00:21,314] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:00:21,315] {logging_mixin.py:109} INFO - [2021-11-01 00:00:21,315] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:00:21,316] {logging_mixin.py:109} INFO - [2021-11-01 00:00:21,316] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:00:21,330] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:00:21,352] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.040 seconds
[2021-11-01 00:00:51,592] {processor.py:163} INFO - Started process (PID=221) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:00:51,611] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:00:51,611] {logging_mixin.py:109} INFO - [2021-11-01 00:00:51,611] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:00:51,613] {logging_mixin.py:109} INFO - [2021-11-01 00:00:51,612] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:00:51,624] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:00:51,630] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.040 seconds
[2021-11-01 00:01:21,697] {processor.py:163} INFO - Started process (PID=276) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:01:21,698] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:01:21,699] {logging_mixin.py:109} INFO - [2021-11-01 00:01:21,699] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:01:21,701] {logging_mixin.py:109} INFO - [2021-11-01 00:01:21,700] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:01:21,718] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:01:21,724] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.030 seconds
[2021-11-01 00:01:52,586] {processor.py:163} INFO - Started process (PID=341) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:01:52,609] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:01:52,610] {logging_mixin.py:109} INFO - [2021-11-01 00:01:52,610] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:01:52,611] {logging_mixin.py:109} INFO - [2021-11-01 00:01:52,611] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:01:52,624] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:01:52,630] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.046 seconds
[2021-11-01 00:02:23,425] {processor.py:163} INFO - Started process (PID=395) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:02:23,451] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:02:23,451] {logging_mixin.py:109} INFO - [2021-11-01 00:02:23,451] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:02:23,465] {logging_mixin.py:109} INFO - [2021-11-01 00:02:23,464] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:02:23,476] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:02:23,482] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.059 seconds
[2021-11-01 00:02:54,383] {processor.py:163} INFO - Started process (PID=460) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:02:54,410] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:02:54,410] {logging_mixin.py:109} INFO - [2021-11-01 00:02:54,410] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:02:54,424] {logging_mixin.py:109} INFO - [2021-11-01 00:02:54,411] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:02:54,436] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:02:54,442] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.061 seconds
[2021-11-01 00:04:09,953] {processor.py:163} INFO - Started process (PID=35) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:04:09,954] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:04:09,955] {logging_mixin.py:109} INFO - [2021-11-01 00:04:09,955] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:04:09,956] {logging_mixin.py:109} INFO - [2021-11-01 00:04:09,956] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:04:09,969] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:04:09,976] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.025 seconds
[2021-11-01 00:04:40,748] {processor.py:163} INFO - Started process (PID=99) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:04:40,762] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:04:40,762] {logging_mixin.py:109} INFO - [2021-11-01 00:04:40,762] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:04:40,764] {logging_mixin.py:109} INFO - [2021-11-01 00:04:40,763] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:04:40,776] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:04:40,782] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.036 seconds
[2021-11-01 00:05:11,224] {processor.py:163} INFO - Started process (PID=153) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:05:11,262] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:05:11,263] {logging_mixin.py:109} INFO - [2021-11-01 00:05:11,263] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:05:11,264] {logging_mixin.py:109} INFO - [2021-11-01 00:05:11,263] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:05:11,276] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:05:11,282] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.061 seconds
[2021-11-01 00:05:41,516] {processor.py:163} INFO - Started process (PID=218) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:05:41,557] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:05:41,557] {logging_mixin.py:109} INFO - [2021-11-01 00:05:41,557] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:05:41,558] {logging_mixin.py:109} INFO - [2021-11-01 00:05:41,558] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:05:41,570] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:05:41,576] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.062 seconds
[2021-11-01 00:06:11,834] {processor.py:163} INFO - Started process (PID=273) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:06:11,876] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:06:11,877] {logging_mixin.py:109} INFO - [2021-11-01 00:06:11,877] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:06:11,878] {logging_mixin.py:109} INFO - [2021-11-01 00:06:11,878] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:06:11,890] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:06:11,895] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.063 seconds
[2021-11-01 00:06:42,172] {processor.py:163} INFO - Started process (PID=337) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:06:42,173] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:06:42,173] {logging_mixin.py:109} INFO - [2021-11-01 00:06:42,173] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:06:42,175] {logging_mixin.py:109} INFO - [2021-11-01 00:06:42,174] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:06:42,186] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:06:42,191] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.021 seconds
[2021-11-01 00:07:12,343] {processor.py:163} INFO - Started process (PID=391) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:07:12,347] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:07:12,348] {logging_mixin.py:109} INFO - [2021-11-01 00:07:12,348] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:07:12,349] {logging_mixin.py:109} INFO - [2021-11-01 00:07:12,349] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:07:12,362] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:07:12,368] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.027 seconds
[2021-11-01 00:07:43,050] {processor.py:163} INFO - Started process (PID=455) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:07:43,056] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:07:43,057] {logging_mixin.py:109} INFO - [2021-11-01 00:07:43,057] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:07:43,058] {logging_mixin.py:109} INFO - [2021-11-01 00:07:43,058] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:07:43,070] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:07:43,076] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.027 seconds
[2021-11-01 00:08:13,799] {processor.py:163} INFO - Started process (PID=509) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:08:13,800] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:08:13,800] {logging_mixin.py:109} INFO - [2021-11-01 00:08:13,800] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:08:13,802] {logging_mixin.py:109} INFO - [2021-11-01 00:08:13,801] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:08:13,814] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:08:13,819] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.022 seconds
[2021-11-01 00:08:44,181] {processor.py:163} INFO - Started process (PID=572) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:08:44,182] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:08:44,183] {logging_mixin.py:109} INFO - [2021-11-01 00:08:44,183] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:08:44,184] {logging_mixin.py:109} INFO - [2021-11-01 00:08:44,184] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:08:44,200] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:08:44,205] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.026 seconds
[2021-11-01 00:09:14,742] {processor.py:163} INFO - Started process (PID=630) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:09:14,752] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:09:14,753] {logging_mixin.py:109} INFO - [2021-11-01 00:09:14,753] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:09:14,754] {logging_mixin.py:109} INFO - [2021-11-01 00:09:14,753] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:09:14,766] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:09:14,771] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.031 seconds
[2021-11-01 00:09:45,596] {processor.py:163} INFO - Started process (PID=694) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:09:45,607] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:09:45,608] {logging_mixin.py:109} INFO - [2021-11-01 00:09:45,608] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:09:45,609] {logging_mixin.py:109} INFO - [2021-11-01 00:09:45,609] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:09:45,621] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:09:45,627] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.034 seconds
[2021-11-01 00:10:16,362] {processor.py:163} INFO - Started process (PID=750) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:10:16,375] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:10:16,376] {logging_mixin.py:109} INFO - [2021-11-01 00:10:16,376] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:10:16,377] {logging_mixin.py:109} INFO - [2021-11-01 00:10:16,377] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:10:16,388] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:10:16,393] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.033 seconds
[2021-11-01 00:10:46,872] {processor.py:163} INFO - Started process (PID=815) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:10:46,886] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:10:46,886] {logging_mixin.py:109} INFO - [2021-11-01 00:10:46,886] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:10:46,888] {logging_mixin.py:109} INFO - [2021-11-01 00:10:46,887] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:10:46,900] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:10:46,905] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.036 seconds
[2021-11-01 00:11:17,443] {processor.py:163} INFO - Started process (PID=870) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:11:17,459] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:11:17,459] {logging_mixin.py:109} INFO - [2021-11-01 00:11:17,459] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:11:17,461] {logging_mixin.py:109} INFO - [2021-11-01 00:11:17,460] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:11:17,471] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:11:17,479] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.038 seconds
[2021-11-01 00:11:48,270] {processor.py:163} INFO - Started process (PID=933) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:11:48,287] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:11:48,288] {logging_mixin.py:109} INFO - [2021-11-01 00:11:48,288] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:11:48,289] {logging_mixin.py:109} INFO - [2021-11-01 00:11:48,289] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:11:48,301] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:11:48,308] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.040 seconds
[2021-11-01 00:12:18,929] {processor.py:163} INFO - Started process (PID=990) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:12:18,947] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:12:18,948] {logging_mixin.py:109} INFO - [2021-11-01 00:12:18,947] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:12:18,949] {logging_mixin.py:109} INFO - [2021-11-01 00:12:18,948] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:12:18,961] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:12:18,967] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.043 seconds
[2021-11-01 00:12:49,692] {processor.py:163} INFO - Started process (PID=1052) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:12:49,712] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:12:49,712] {logging_mixin.py:109} INFO - [2021-11-01 00:12:49,712] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:12:49,713] {logging_mixin.py:109} INFO - [2021-11-01 00:12:49,713] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:12:49,725] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:12:49,730] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.040 seconds
[2021-11-01 00:13:20,203] {processor.py:163} INFO - Started process (PID=1108) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:13:20,224] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:13:20,224] {logging_mixin.py:109} INFO - [2021-11-01 00:13:20,224] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:13:20,226] {logging_mixin.py:109} INFO - [2021-11-01 00:13:20,225] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:13:20,238] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:13:20,242] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.042 seconds
[2021-11-01 00:13:50,989] {processor.py:163} INFO - Started process (PID=1171) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:13:50,997] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:13:50,997] {logging_mixin.py:109} INFO - [2021-11-01 00:13:50,997] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:13:50,998] {logging_mixin.py:109} INFO - [2021-11-01 00:13:50,998] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:13:51,009] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:13:51,015] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.028 seconds
[2021-11-01 00:14:21,064] {processor.py:163} INFO - Started process (PID=1229) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:14:21,088] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:14:21,089] {logging_mixin.py:109} INFO - [2021-11-01 00:14:21,089] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:14:21,090] {logging_mixin.py:109} INFO - [2021-11-01 00:14:21,090] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:14:21,101] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:14:21,107] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.045 seconds
[2021-11-01 00:14:51,821] {processor.py:163} INFO - Started process (PID=1283) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:14:51,851] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:14:51,851] {logging_mixin.py:109} INFO - [2021-11-01 00:14:51,851] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:14:51,852] {logging_mixin.py:109} INFO - [2021-11-01 00:14:51,852] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:14:51,864] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:14:51,868] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.050 seconds
[2021-11-01 00:15:21,892] {processor.py:163} INFO - Started process (PID=1347) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:15:21,920] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:15:21,920] {logging_mixin.py:109} INFO - [2021-11-01 00:15:21,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:15:21,921] {logging_mixin.py:109} INFO - [2021-11-01 00:15:21,921] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:15:21,933] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:15:21,940] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.051 seconds
[2021-11-01 00:15:51,956] {processor.py:163} INFO - Started process (PID=1401) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:15:51,985] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:15:51,986] {logging_mixin.py:109} INFO - [2021-11-01 00:15:51,986] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:15:51,987] {logging_mixin.py:109} INFO - [2021-11-01 00:15:51,987] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:15:51,999] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:15:52,005] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.051 seconds
[2021-11-01 00:20:14,260] {processor.py:163} INFO - Started process (PID=44) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:20:14,261] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:20:14,262] {logging_mixin.py:109} INFO - [2021-11-01 00:20:14,262] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:20:14,264] {logging_mixin.py:109} INFO - [2021-11-01 00:20:14,263] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:20:14,280] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:20:14,288] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.031 seconds
[2021-11-01 00:20:49,297] {processor.py:163} INFO - Started process (PID=459) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:20:49,298] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:20:49,299] {logging_mixin.py:109} INFO - [2021-11-01 00:20:49,298] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:20:49,300] {logging_mixin.py:109} INFO - [2021-11-01 00:20:49,299] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:20:49,311] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:20:49,317] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.022 seconds
[2021-11-01 00:21:20,187] {processor.py:163} INFO - Started process (PID=530) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:21:20,199] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:21:20,199] {logging_mixin.py:109} INFO - [2021-11-01 00:21:20,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:21:20,200] {logging_mixin.py:109} INFO - [2021-11-01 00:21:20,200] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:21:20,212] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:21:20,217] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.032 seconds
[2021-11-01 00:21:50,465] {processor.py:163} INFO - Started process (PID=584) to work on /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:21:50,478] {processor.py:620} INFO - Processing file /opt/airflow/dags/checkingmodel.py for tasks to queue
[2021-11-01 00:21:50,479] {logging_mixin.py:109} INFO - [2021-11-01 00:21:50,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:21:50,480] {logging_mixin.py:109} INFO - [2021-11-01 00:21:50,479] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/checkingmodel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/checkingmodel.py", line 29
    AIRFLOW_HOME = os.getenv('AIRFLOW_HOME')
               ^
IndentationError: expected an indented block
[2021-11-01 00:21:50,494] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/checkingmodel.py
[2021-11-01 00:21:50,501] {processor.py:171} INFO - Processing /opt/airflow/dags/checkingmodel.py took 0.039 seconds
