[2021-10-30 20:58:08,323] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.populate_passenger_table manual__2021-10-30T20:58:05.339391+00:00 [queued]>
[2021-10-30 20:58:08,358] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.populate_passenger_table manual__2021-10-30T20:58:05.339391+00:00 [queued]>
[2021-10-30 20:58:08,358] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-30 20:58:08,358] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-30 20:58:08,359] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-30 20:58:08,381] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): populate_passenger_table> on 2021-10-30 20:58:05.339391+00:00
[2021-10-30 20:58:08,395] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'populate_passenger_table', 'manual__2021-10-30T20:58:05.339391+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/checkingmodel.py', '--cfg-path', '/tmp/tmpf96azu9i', '--error-file', '/tmp/tmp18sauf2l']
[2021-10-30 20:58:08,396] {standard_task_runner.py:77} INFO - Job 14: Subtask populate_passenger_table
[2021-10-30 20:58:08,390] {standard_task_runner.py:52} INFO - Started process 533 to run task
[2021-10-30 20:58:08,474] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.populate_passenger_table manual__2021-10-30T20:58:05.339391+00:00 [running]> on host ebed9469addd
[2021-10-30 20:58:08,560] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=populate_passenger_table
AIRFLOW_CTX_EXECUTION_DATE=2021-10-30T20:58:05.339391+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-30T20:58:05.339391+00:00
[2021-10-30 20:58:08,576] {base.py:79} INFO - Using connection to: id: postgres_default. Host: 172.22.0.2, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-10-30 20:58:08,583] {dbapi.py:225} INFO - Running statement: COPY passengers FROM '/opt/***/dags/test.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2021-10-30 20:58:08,585] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 69, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/dags/test.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2021-10-30 20:58:08,608] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=my_dag, task_id=populate_passenger_table, execution_date=20211030T205805, start_date=20211030T205808, end_date=20211030T205808
[2021-10-30 20:58:08,631] {standard_task_runner.py:91} ERROR - Failed to execute job 14 for task populate_passenger_table
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 69, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/dags/test.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2021-10-30 20:58:08,656] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-30 20:58:08,745] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
